# Generated by Django 5.2 on 2026-04-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_username_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='limit_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='limit_requests',
            field=models.PositiveIntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='requests',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
