# Generated by Django 5.2 on 2026-04-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_is_premium_users_limit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='limit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
