# Generated by Django 5.2 on 2026-04-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_limit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='limit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
