# Generated by Django 5.2 on 2026-04-07 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_limit_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
